@startuml
title 桥接模式时序图

actor Client
participant RefinedAbstraction
participant ConImplementor

activate Client
Client -> ConImplementor: <<create>>
Client -> RefinedAbstraction: <<create with ConImplementor>>
Client -> RefinedAbstraction: operation()
activate RefinedAbstraction
RefinedAbstraction -> ConImplementor: operationImpl()
activate ConImplementor
@enduml
