@startuml
title 代理模式时序图

actor Client
participant Proxy
participant RealSubject

activate Client
Client -> Proxy: request()
activate Proxy
Proxy -> Proxy: preRequest()
Proxy -> RealSubject: request()
activate RealSubject
deactivate RealSubject
Proxy -> Proxy: afterRequest()
@enduml